import type { CourtOsResponsibilityDesignKey } from "./courtosInformationArchitecture";

export type CourtOsResponsibilityDataPosture =
  | "read_ready"
  | "conditional_empty"
  | "withheld_fail_closed";

export interface CourtOsResponsibilityWorkspaceSourceV1 {
  responsibility: CourtOsResponsibilityDesignKey;
  packageId: string;
  posture: CourtOsResponsibilityDataPosture;
  currentState: string;
  evidence: readonly string[];
  boundary: string;
}

/**
 * Semantic routing for the admitted Foundation A UAT1 packages. Counts and
 * House-scoped owners remain in their source projections; this catalog only
 * declares which admitted package owns each current responsibility surface.
 */
export const COURTOS_RESPONSIBILITY_WORKSPACE_SOURCES: readonly CourtOsResponsibilityWorkspaceSourceV1[] = [
  { responsibility: "office_post_appointments", packageId: "phase_five_information_governance_second_batch_uat1_v1", posture: "read_ready", currentState: "Current appointment scopes and accountable holders are available for planning review.", evidence: ["Office and post assignment register", "Appointing-scope authority evidence"], boundary: "Appointment, removal, office creation, title, and remuneration execution remain outside UAT1." },
  { responsibility: "household_stores_provisioning_procurement", packageId: "foundation_a_household_uat1_release_v1", posture: "read_ready", currentState: "House positions, manor Food capacity, custody context, and the approved prior-cycle economic evidence are available.", evidence: ["Opening Stores positions", "1117–1119 economic activity evidence", "House-to-manor custody binding"], boundary: "No personal consumption ledger or new movement, reservation, settlement, or receipt is inferred." },
  { responsibility: "adult_kin_support", packageId: "foundation_a_household_uat1_release_v1", posture: "read_ready", currentState: "Explicit managed-adult eligibility, support basis, residence context, manager, and resolved arrangements are available.", evidence: ["Adult Kin support roster", "Support arrangement register", "Household membership and residence context"], boundary: "Residence never implies support; individually ambiguous provision links remain withheld." },
  { responsibility: "education_formation", packageId: "foundation_a_household_uat1_release_v1", posture: "read_ready", currentState: "Current learner arrangements, provider and host context, authority, and the admitted prior-cycle report projection are available.", evidence: ["Education arrangement register", "1117–1119 annual structured receipts", "Responsible-party cycle reports"], boundary: "No runtime formation, capacity promise, observed-history claim, or ART mutation." },
  { responsibility: "household_service_care", packageId: "foundation_a_household_uat1_release_v1", posture: "read_ready", currentState: "The manager-bound care roster, current conditions, specialized commitments, and prior-cycle care reports are available.", evidence: ["Health and care roster", "Specialized care commitments", "1117–1119 responsible-manager reports"], boundary: "No treatment, mortality, or health execution occurs in UAT1." },
  { responsibility: "marriage_dynasty_stewardship", packageId: "phase_five_marriage_dynasty_uat1_admission_v1", posture: "read_ready", currentState: "Current people, unions, kinship, succession, contract exposure, obligations, and marriage authority are available.", evidence: ["Current marriage subjects and union graph", "Succession and tenure context", "Contract, obligation, and clearance evidence"], boundary: "Search, offer, betrothal, clearance, ceremony, residence, fertility, and succession execution remain outside UAT1." },
  { responsibility: "patronage_hospitality_gifts", packageId: "phase_five_marriage_dynasty_uat1_admission_v1", posture: "read_ready", currentState: "House accountability and the opening patronage and hospitality policy posture are available.", evidence: ["Patronage authority assignment", "House and relationship context", "Opening policy posture"], boundary: "No visit, guest stay, gift transfer, Journey, or realized obligation is invented." },
  { responsibility: "manor_stewardship", packageId: "phase_five_manor_operations_uat1_admission_v1", posture: "read_ready", currentState: "Manor-scoped stewardship, physical-condition observations, facilities, and project context are available.", evidence: ["Four-bucket manor assignment register", "Condition observation register", "Facility and project evidence"], boundary: "Stewardship does not imply fiscal, security, works, or project authority." },
  { responsibility: "estate_fabric_maintenance_oversight", packageId: "phase_five_manor_operations_uat1_admission_v1", posture: "read_ready", currentState: "Estate surfaces, observed condition, linked projects, and accountable maintenance context are available.", evidence: ["Estate condition observations", "Facility registry", "Project linkage evidence"], boundary: "No repair execution, material commitment, Journey, or general-ledger posting." },
  { responsibility: "works_project_supervision", packageId: "phase_five_conditional_estate_governance_uat1_admission_v1", posture: "read_ready", currentState: "Exact project-scoped assignments and referenced project records are available where a project exists.", evidence: ["Works assignment register", "Project reconstruction evidence", "Parent-manor scope"], boundary: "The workspace cannot create a project, spend resources, or duplicate the works engine." },
  { responsibility: "franchise_operations", packageId: "phase_five_conditional_estate_governance_uat1_admission_v1", posture: "read_ready", currentState: "Exact facility-scoped franchise assignments and operating contexts are available where a facility exists.", evidence: ["Franchise assignment register", "Discrete facility registry", "Facility and right context"], boundary: "No facility, operator, right, revenue, or operating result is inferred." },
  { responsibility: "portfolio_oversight", packageId: "phase_five_conditional_estate_governance_uat1_admission_v1", posture: "read_ready", currentState: "Derived multi-manor applicability and exact admitted portfolio assignments are available for eligible Houses.", evidence: ["Portfolio applicability register", "House-to-manor scope", "Admitted portfolio assignment context"], boundary: "Portfolio oversight does not duplicate or replace manor-level operation." },
  { responsibility: "house_fiscal_administration", packageId: "phase_five_resources_finance_uat1_admission_v1", posture: "read_ready", currentState: "House fiscal ownership, opening balances, custody rollups, and flow-family posture are available.", evidence: ["Fiscal authority assignment", "Opening balance and custody rollups", "Flow-family and treasury-proxy evidence"], boundary: "No settlement, payment, transfer, reconciliation, or posting occurs in UAT1." },
  { responsibility: "manor_fiscal_administration", packageId: "phase_five_resources_finance_uat1_admission_v1", posture: "read_ready", currentState: "Manor fiscal ownership, custody context, and remittance posture are available at admitted manor scopes.", evidence: ["Manor fiscal authority assignment", "House-to-manor scope", "Custody and remittance context"], boundary: "No local treasury, transfer, or operator authority is inferred." },
  { responsibility: "revenue_right_administration_collection", packageId: "phase_five_conditional_estate_governance_uat1_admission_v1", posture: "conditional_empty", currentState: "The responsibility workspace is open, but no exact current revenue-right instance is admitted for this House scope.", evidence: ["Revenue-right candidate register", "Withholding and predicate evidence"], boundary: "Candidate rights and collection contexts remain withheld; no right or collection is invented." },
  { responsibility: "reception_intake", packageId: "phase_five_information_governance_second_batch_uat1_v1", posture: "withheld_fail_closed", currentState: "The intake workspace is present, while ambiguous opening reception anchors remain explicitly withheld.", evidence: ["Reception anchor withholding docket", "Correspondence entity and operator context"], boundary: "No host, location, acceptance, recipient, or consequential intake is inferred." },
  { responsibility: "records_archives", packageId: "phase_five_records_correspondence_uat1_admission_v1", posture: "read_ready", currentState: "Record families, custody posture, provenance, verification posture, and archive boundaries are available.", evidence: ["Record-family catalog", "Verification posture register", "Source and custody provenance"], boundary: "Church-owned records remain Church-owned; absence of a record is not converted into a fact." },
  { responsibility: "correspondence_dispatch", packageId: "phase_five_records_correspondence_uat1_admission_v1", posture: "read_ready", currentState: "Correspondence entities, eligible operators, compact lookback, lifecycle semantics, and explicit fail-closed entities are available.", evidence: ["Correspondence entity and operator state", "Lifecycle event and purpose registries", "Compacted lookback reports"], boundary: "No delivery, House Knowledge grant, route, recipient, transactional receipt, or player-readable machine prose is inferred." },
  { responsibility: "security_asset_protection", packageId: "phase_five_security_readiness_uat1_admission_v1", posture: "read_ready", currentState: "Security assignments, facilities, named posts, custody functions, and fortification posture are available.", evidence: ["Security authority assignments", "Facility and fortification profiles", "Named-post and functional-custody registers"], boundary: "No guard activation, tactical action, equipment issue, Journey, or economic posting." },
  { responsibility: "martial_readiness_training", packageId: "phase_five_security_readiness_uat1_admission_v1", posture: "read_ready", currentState: "House readiness ownership and manor service, training, and muster posture are available.", evidence: ["Readiness authority assignments", "Martial service claims", "Training and muster posture"], boundary: "No call-to-arms, tactical execution, or generated service event." },
  { responsibility: "martial_stores_horse_capacity", packageId: "phase_five_security_readiness_uat1_admission_v1", posture: "read_ready", currentState: "Martial-store accountability and directional equipment, horse, and capacity posture are available.", evidence: ["Martial stores authority assignments", "Equipment readiness register", "Horse-capacity and payer-reconciliation context"], boundary: "Directional capacity is not a horse or equipment inventory and cannot authorize procurement." },
  { responsibility: "external_relations_representation", packageId: "phase_five_information_governance_second_batch_uat1_v1", posture: "read_ready", currentState: "House ownership, active targets, named delegates, relationship provenance, and correspondence compatibility are available.", evidence: ["External Relations owner register", "Active target and delegate portfolios", "Lens, bias, provenance, and action-bound metadata"], boundary: "No relationship history, ART mutation, diplomatic result, or House Knowledge is inferred." },
  { responsibility: "household_observance_chaplaincy", packageId: "phase_five_church_observance_rights_uat1_admission_v1", posture: "read_ready", currentState: "House observance accountability, parish route, provider context, and support posture are available.", evidence: ["Observance authority assignment", "Parish and support registers", "Church institution surface"], boundary: "House assignment does not confer Church authority or create a rite, benefice, or institution." },
  { responsibility: "church_rights_institutional_affairs", packageId: "phase_five_church_observance_rights_uat1_admission_v1", posture: "conditional_empty", currentState: "The institutional-rights workspace is open, but no exact current Church-right instance is admitted.", evidence: ["Church-right predicate catalog", "House-side evidence docket", "Historical clearance evidence"], boundary: "Candidate patronage rights, seats, cases, and Church authority remain withheld fail-closed." },
] as const;

export function responsibilityWorkspaceSource(
  responsibility: CourtOsResponsibilityDesignKey,
): CourtOsResponsibilityWorkspaceSourceV1 {
  const source = COURTOS_RESPONSIBILITY_WORKSPACE_SOURCES.find(
    (candidate) => candidate.responsibility === responsibility,
  );
  if (!source) throw new Error(`No UAT1 workspace source owns ${responsibility}.`);
  return source;
}
